matrix:
  include:
    - language: python
      python: 3.6
      cache: pip
      script: make test-python

    - language: C
      compiler: swig
      script: make compile-c

    - language: rust
      cache: cargo
      script: make compile-rust
